#!/bin/bash
# make sym links in ~/bin

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

UPDATELOC=$SCRIPTPATH/update-loc
WEATHERPY=$SCRIPTPATH/weather-location.py

chmod +x "$UPDATELOC"
chmod +x "$WEATHERPY"

mkdir -p ~/bin

ln -sf $UPDATELOC ~/bin/update-loc
ln -sf $WEATHERPY ~/bin/weather-location

